import type {
  KPICardData,
  FunnelStageData,
  RevenuePoint,
  Conversation,
  ActivityEvent,
  Booking,
  Recommendation,
  SystemStatus,
  EvaluationMetric,
  KnowledgeDocument,
  LeadItem,
} from "./types"

export const kpiCards: KPICardData[] = [
  {
    id: "revenue_opp",
    label: "Revenue Opportunity",
    value: "₹5,42,000",
    change: 12.4,
    trend: "up",
    sparkline: [380000, 410000, 435000, 480000, 465000, 510000, 542000],
    subtext: "vs previous 7 days",
  },
  {
    id: "hot_leads",
    label: "Hot Leads",
    value: "42",
    change: 8.0,
    trend: "up",
    sparkline: [32, 34, 30, 36, 35, 39, 42],
    subtext: "vs previous 7 days",
  },
  {
    id: "conv_rate",
    label: "Conversion Rate",
    value: "24.8%",
    change: 2.1,
    trend: "up",
    sparkline: [22.1, 22.8, 23.4, 23.1, 23.9, 24.2, 24.8],
    subtext: "vs previous 7 days",
  },
  {
    id: "ai_confidence",
    label: "AI Confidence",
    value: "94.2%",
    change: 0.5,
    trend: "up",
    sparkline: [93.2, 93.5, 93.8, 93.6, 94.0, 93.9, 94.2],
    subtext: "vs previous 7 days",
  },
]

export const funnelStages: FunnelStageData[] = [
  { stage: "New", count: 120, value: 1200000, conversionRate: 100, avgTime: "1.2h" },
  { stage: "Engaged", count: 85, value: 850000, conversionRate: 70.8, avgTime: "4.5h" },
  { stage: "Qualified", count: 52, value: 520000, conversionRate: 61.1, avgTime: "1.5d" },
  { stage: "Booked", count: 32, value: 320000, conversionRate: 61.5, avgTime: "12h" },
  { stage: "Converted", count: 24, value: 240000, conversionRate: 75.0, avgTime: "2.1d" },
]

export const revenueData: RevenuePoint[] = [
  { date: "Jun 12", actual: 8500, forecasted: 9000 },
  { date: "Jun 14", actual: 11000, forecasted: 10000 },
  { date: "Jun 16", actual: 9500, forecasted: 10500 },
  { date: "Jun 18", actual: 12000, forecasted: 11000 },
  { date: "Jun 20", actual: 14500, forecasted: 12000 },
  { date: "Jun 22", actual: 13000, forecasted: 12500 },
  { date: "Jun 24", actual: 15500, forecasted: 13000 },
  { date: "Jun 26", actual: 17000, forecasted: 14000 },
  { date: "Jun 28", actual: 14000, forecasted: 14500 },
  { date: "Jun 30", actual: 16500, forecasted: 15000 },
  { date: "Jul 02", actual: 18500, forecasted: 16000 },
  { date: "Jul 04", actual: 21000, forecasted: 17500 },
  { date: "Jul 06", actual: 19000, forecasted: 18000 },
  { date: "Jul 08", actual: 22500, forecasted: 19000 },
  { date: "Jul 10", actual: 25400, forecasted: 20500 },
]

export const recentConversations: Conversation[] = [
  {
    id: "conv_1",
    customerName: "Rohan Sharma",
    phoneNumber: "+91 98450 12345",
    avatar: "RS",
    lastMessage: "Do you have personal training slots open tomorrow at 7 AM? I need to focus on lower body rehab.",
    timestamp: "2m ago",
    intent: "high-intent",
    status: "active",
    unread: true,
    value: 18000,
    messages: [
      { id: "m1_1", sender: "customer", content: "Hi, I am looking for personal training. Do you have slots open tomorrow at 7 AM?", timestamp: "Yesterday, 06:12 PM" },
      { id: "m1_2", sender: "ai", content: "Hello Rohan! Yes, we have personal training slots open tomorrow at 7 AM with Coach Amit. Would you like me to book it for you?", timestamp: "Yesterday, 06:13 PM" },
      { id: "m1_3", sender: "customer", content: "Yes, please. How much is the fee?", timestamp: "Yesterday, 06:14 PM" },
      { id: "m1_4", sender: "ai", content: "The single session fee is ₹1,800. We also have monthly packages starting at ₹18,000 for 12 sessions. Should I book the single session for tomorrow?", timestamp: "Yesterday, 06:15 PM" },
      { id: "m1_5", sender: "customer", content: "Yes, book the single session first. I will check the package later.", timestamp: "Yesterday, 06:16 PM" },
      { id: "m1_6", sender: "ai", content: "Perfect! I have booked your Sports Physiotherapy/Personal Training session for tomorrow at 7 AM. Here is your booking reference: B-142.", timestamp: "Yesterday, 06:17 PM" },
      { id: "m1_7", sender: "customer", content: "Thanks.", timestamp: "Yesterday, 06:18 PM" },
      { id: "m1_8", sender: "customer", content: "Do you have personal training slots open tomorrow at 7 AM? I need to focus on lower body rehab.", timestamp: "2m ago" },
    ],
  },
  {
    id: "conv_2",
    customerName: "Dr. Ananya Iyer",
    phoneNumber: "+91 99160 88776",
    avatar: "AI",
    lastMessage: "Is the clinical nutritionist available for consultations on Saturday? I want to share my blood reports.",
    timestamp: "12m ago",
    intent: "high-intent",
    status: "active",
    pendingAI: true,
    value: 25000,
    messages: [
      { id: "m2_1", sender: "customer", content: "Hello, I wanted to inquire about custom metabolic diets.", timestamp: "Today, 07:10 PM" },
      { id: "m2_2", sender: "ai", content: "Hi Dr. Ananya! We offer metabolic assessments and customized clinical nutrition diet charts. Our senior clinical nutritionist is available for personal consultation slots.", timestamp: "Today, 07:11 PM" },
      { id: "m2_3", sender: "customer", content: "Is the clinical nutritionist available for consultations on Saturday? I want to share my blood reports.", timestamp: "12m ago" },
    ],
  },
  {
    id: "conv_3",
    customerName: "Vikram Malhotra",
    phoneNumber: "+91 96112 55443",
    avatar: "VM",
    lastMessage: "Thanks, the diet plan pdf downloaded successfully. I'll review it and get back to you.",
    timestamp: "1h ago",
    intent: "follow-up",
    status: "inactive",
    value: 12000,
    messages: [
      { id: "m3_1", sender: "customer", content: "Hey, can you send the nutrition plan you drafted last week? I lost the document link.", timestamp: "Today, 05:30 PM" },
      { id: "m3_2", sender: "ai", content: "Hi Vikram! Sure, I've compiled your customized nutrition chart and diet plan. Here is the download link: veda.fit/vikram-diet-plan.pdf", timestamp: "Today, 05:32 PM" },
      { id: "m3_3", sender: "customer", content: "Thanks, the diet plan pdf downloaded successfully. I'll review it and get back to you.", timestamp: "1h ago" },
    ],
  },
  {
    id: "conv_4",
    customerName: "Priya Nair",
    phoneNumber: "+91 97312 99881",
    avatar: "PN",
    lastMessage: "What are your membership rates for the annual wellness package?",
    timestamp: "3h ago",
    intent: "high-intent",
    status: "active",
    unread: true,
    value: 45000,
    messages: [
      { id: "m4_1", sender: "customer", content: "Hi there! I wanted to check out your wellness packages.", timestamp: "Today, 03:52 PM" },
      { id: "m4_2", sender: "ai", content: "Hello! We offer premium physical assessment sessions, medical gym memberships, and annual wellness coaching. Which one would you like to explore?", timestamp: "Today, 03:53 PM" },
      { id: "m4_3", sender: "customer", content: "What are your membership rates for the annual wellness package?", timestamp: "3h ago" },
    ],
  },
  {
    id: "conv_5",
    customerName: "Arjun Mehta",
    phoneNumber: "+91 95350 77665",
    avatar: "AM",
    lastMessage: "Can I reschedule my physio session from today to Thursday?",
    timestamp: "5h ago",
    intent: "support",
    status: "active",
    value: 8500,
    messages: [
      { id: "m5_1", sender: "customer", content: "Can I reschedule my physio session from today to Thursday?", timestamp: "5h ago" },
      { id: "m5_2", sender: "staff", content: "Hi Arjun, this is Coach Amit. I have rescheduled your Sports Physiotherapy slot to this Thursday at 10 AM. Let me know if that works.", timestamp: "4.5h ago" },
    ],
  },
  {
    id: "conv_6",
    customerName: "Kavita Reddy",
    phoneNumber: "+91 94480 33221",
    avatar: "KR",
    lastMessage: "Is parking available at the Indiranagar branch?",
    timestamp: "1d ago",
    intent: "cold",
    status: "closed",
    value: 15000,
    messages: [
      { id: "m6_1", sender: "customer", content: "Is parking available at the Indiranagar branch?", timestamp: "1d ago" },
      { id: "m6_2", sender: "ai", content: "Hi Kavita! Yes, free dedicated basement parking is available for all members at our Indiranagar center. Valet assistance is also provided.", timestamp: "1d ago" },
    ],
  },
  {
    id: "conv_7",
    customerName: "Devendra Singh",
    phoneNumber: "+91 98765 43210",
    avatar: "DS",
    lastMessage: "I'll discuss with my HR head and revert. Thanks.",
    timestamp: "2d ago",
    intent: "follow-up",
    status: "inactive",
    value: 120000,
    messages: [
      { id: "m7_1", sender: "customer", content: "Hi, do you offer corporate packages for physical rehabilitation?", timestamp: "July 08, 10:00 AM" },
      { id: "m7_2", sender: "ai", content: "Hello Devendra! Yes, Veda Wellness offers corporate memberships and specialized clinical rehabilitation packages for employees.", timestamp: "July 08, 10:02 AM" },
      { id: "m7_3", sender: "customer", content: "What are the rates for a group of 25 employees?", timestamp: "July 08, 10:15 AM" },
      { id: "m7_4", sender: "ai", content: "For a group of 25, we offer a 20% discount on assessments and standard monthly rehabilitation packages. I can email a custom quote.", timestamp: "July 08, 10:17 AM" },
      { id: "m7_5", sender: "customer", content: "Yes please, send it to devendra@corporatesolutions.com", timestamp: "July 08, 10:20 AM" },
      { id: "m7_6", sender: "ai", content: "Sent! Please check your email. I've detailed the custom rehab pricing schedule there.", timestamp: "July 08, 10:25 AM" },
      { id: "m7_7", sender: "customer", content: "I'll discuss with my HR head and revert. Thanks.", timestamp: "July 08, 11:00 AM" },
    ],
  },
  {
    id: "conv_8",
    customerName: "Meera Nair",
    phoneNumber: "+91 97654 32109",
    avatar: "MN",
    lastMessage: "Great, found it. Thanks for the map link.",
    timestamp: "1d ago",
    intent: "cold",
    status: "inactive",
    value: 0,
    messages: [
      { id: "m8_1", sender: "customer", content: "Hi, where is your Whitefield center located? I'm near the ITPL main gate.", timestamp: "July 10, 11:30 AM" },
      { id: "m8_2", sender: "ai", content: "Hi Meera! Our Whitefield branch is located on the Inner Ring Road, just 1.5 km from ITPL main gate. Here is the Google Maps link: veda.fit/whitefield-map", timestamp: "July 10, 11:31 AM" },
      { id: "m8_3", sender: "customer", content: "Great, found it. Thanks for the map link.", timestamp: "July 10, 11:35 AM" },
    ],
  },
  {
    id: "conv_9",
    customerName: "Sanjay Singhal",
    phoneNumber: "+91 96543 21098",
    avatar: "SS",
    lastMessage: "Do you have orthopedic coaches specializing in ligament recovery?",
    timestamp: "30m ago",
    intent: "high-intent",
    status: "active",
    value: 30000,
    messages: [
      { id: "m9_1", sender: "customer", content: "Hello, do you provide physio training for ACL rehab?", timestamp: "Today, 06:30 PM" },
      { id: "m9_2", sender: "ai", content: "Hi Sanjay! Yes, we have specialized post-surgery ACL recovery packages. Our senior orthopedic physiotherapists supervise every session.", timestamp: "Today, 06:31 PM" },
      { id: "m9_3", sender: "customer", content: "Do you have orthopedic coaches specializing in ligament recovery?", timestamp: "30m ago" },
    ],
  },
  {
    id: "conv_10",
    customerName: "Pooja Hegde",
    phoneNumber: "+91 95432 10987",
    avatar: "PH",
    lastMessage: "Okay, what is the maximum class size?",
    timestamp: "4h ago",
    intent: "follow-up",
    status: "active",
    value: 12000,
    messages: [
      { id: "m10_1", sender: "customer", content: "Hi, do you have slot availability for clinical yoga?", timestamp: "Today, 02:00 PM" },
      { id: "m10_2", sender: "ai", content: "Hello Pooja! Yes, we have clinical yoga batches running on Tuesday, Thursday, and Saturday mornings at 8 AM. Batches are limited in size for individual focus.", timestamp: "Today, 02:02 PM" },
      { id: "m10_3", sender: "customer", content: "Okay, what is the maximum class size?", timestamp: "4h ago" },
    ],
  },
  {
    id: "conv_11",
    customerName: "Rajesh Khanna",
    phoneNumber: "+91 94321 09876",
    avatar: "RK",
    lastMessage: "Please ensure this is checked. I pay for premium access.",
    timestamp: "2d ago",
    intent: "support",
    status: "closed",
    value: 25000,
    messages: [
      { id: "m11_1", sender: "customer", content: "The air conditioning in the Indiranagar locker room isn't working today. It's very hot.", timestamp: "July 09, 08:30 AM" },
      { id: "m11_2", sender: "staff", content: "Hi Rajesh! Apologies for the inconvenience. A technician has been called and the AC unit is being serviced today.", timestamp: "July 09, 09:00 AM" },
      { id: "m11_3", sender: "customer", content: "Please ensure this is checked. I pay for premium access.", timestamp: "July 09, 09:15 AM" },
    ],
  },
  {
    id: "conv_12",
    customerName: "Neha Deshmukh",
    phoneNumber: "+91 93210 98765",
    avatar: "ND",
    lastMessage: "Yes, 4 PM works for me. Book it.",
    timestamp: "1h ago",
    intent: "high-intent",
    status: "active",
    value: 4500,
    messages: [
      { id: "m12_1", sender: "customer", content: "Hi, I want to book a body composition assessment for tomorrow.", timestamp: "Today, 05:00 PM" },
      { id: "m12_2", sender: "ai", content: "Hello Neha! Sure, we have slots open tomorrow at 10 AM, 1 PM, and 4 PM. Which one would you prefer?", timestamp: "Today, 05:01 PM" },
      { id: "m12_3", sender: "customer", content: "Yes, 4 PM works for me. Book it.", timestamp: "1h ago" },
    ],
  },
]

export const activityFeed: ActivityEvent[] = [
  {
    id: "act_1",
    type: "message_sent",
    title: "AI Response Dispatched",
    description: "Replied to Rohan Sharma on WhatsApp: Confirmed training slot availability and shared booking link.",
    timestamp: "2m ago",
    status: "success",
  },
  {
    id: "act_2",
    type: "lead_scored",
    title: "Lead Scored: 92/100",
    description: "Dr. Ananya Iyer identified as Hot Lead based on nutrition inquiry and high intent context.",
    timestamp: "12m ago",
    status: "success",
  },
  {
    id: "act_3",
    type: "booking_created",
    title: "Appointment Booked",
    description: "Vikram Malhotra confirmed for Elite Rehab Session today at 04:30 PM.",
    timestamp: "1h ago",
    status: "info",
  },
  {
    id: "act_4",
    type: "message_sent",
    title: "New WhatsApp Lead Capture",
    description: "Priya Nair initiated conversation regarding annual wellness packages.",
    timestamp: "3h ago",
    status: "info",
  },
  {
    id: "act_5",
    type: "follow_up",
    title: "Smart Follow-up Sent",
    description: "Automated WhatsApp nudge sent to Amit Patel regarding metabolic assessment draft proposal.",
    timestamp: "4h ago",
    status: "warning",
  },
  {
    id: "act_6",
    type: "lead_converted",
    title: "Lead Converted",
    description: "Arjun Mehta converted to Annual Performance Member (₹45,000 package value).",
    timestamp: "5h ago",
    status: "success",
  },
  {
    id: "act_7",
    type: "revenue_updated",
    title: "Pipeline Revenue Updated",
    description: "Added ₹85,000 to potential opportunity pipeline from 3 new high-intent incoming leads.",
    timestamp: "1d ago",
    status: "neutral",
  },
]

export const bookings: Booking[] = [
  {
    id: "b_1",
    customerName: "Rohan Sharma",
    service: "Sports Physiotherapy",
    timeSlot: "Today, 07:00 AM",
    status: "completed",
    value: 1800,
  },
  {
    id: "b_2",
    customerName: "Dr. Ananya Iyer",
    service: "Nutrition Consultation",
    timeSlot: "Today, 11:30 AM",
    status: "pending",
    value: 2500,
  },
  {
    id: "b_3",
    customerName: "Vikram Malhotra",
    service: "Elite Rehab Training",
    timeSlot: "Today, 04:30 PM",
    status: "confirmed",
    value: 3000,
  },
  {
    id: "b_4",
    customerName: "Priya Nair",
    service: "Diagnostic Assessment",
    timeSlot: "Tomorrow, 09:00 AM",
    status: "confirmed",
    value: 4500,
  },
  {
    id: "b_5",
    customerName: "Amit Patel",
    service: "Metabolic Assessment",
    timeSlot: "Tomorrow, 02:00 PM",
    status: "pending",
    value: 3500,
  },
  {
    id: "b_6",
    customerName: "Devendra Singh",
    service: "Corporate Wellness Review",
    timeSlot: "July 08, 10:00 AM",
    status: "completed",
    value: 12000,
  },
  {
    id: "b_7",
    customerName: "Sanjay Singhal",
    service: "ACL Ligament Rehab",
    timeSlot: "July 12, 11:00 AM",
    status: "confirmed",
    value: 3000,
  },
  {
    id: "b_8",
    customerName: "Pooja Hegde",
    service: "Clinical Yoga Batch",
    timeSlot: "July 12, 08:00 AM",
    status: "pending",
    value: 1500,
  },
  {
    id: "b_9",
    customerName: "Rajesh Khanna",
    service: "Locker Room AC Service Check",
    timeSlot: "July 09, 09:00 AM",
    status: "cancelled",
    value: 0,
  },
  {
    id: "b_10",
    customerName: "Neha Deshmukh",
    service: "Body Composition Analysis",
    timeSlot: "Tomorrow, 04:00 PM",
    status: "confirmed",
    value: 4500,
  },
  {
    id: "b_11",
    customerName: "Shreya Ghoshal",
    service: "Metabolic Scan Assessment",
    timeSlot: "July 10, 02:30 PM",
    status: "completed",
    value: 6500,
  },
  {
    id: "b_12",
    customerName: "Sunita Williams",
    service: "Cardiac Rehab Consultation",
    timeSlot: "July 13, 03:00 PM",
    status: "pending",
    value: 5000,
  },
]

export const recommendations: Recommendation[] = [
  {
    id: "rec_1",
    title: "3 High-Intent Leads inactive for 24h",
    description: "Rohan Sharma, Priya Nair, and Amit Patel have questions about personal coaching schedules. Tap to draft follow-up.",
    priority: "high",
    actionLabel: "Review Drafts",
  },
  {
    id: "rec_2",
    title: "Optimize WhatsApp KB: Saturday nutritionist availability",
    description: "5 customer questions received this week about weekend hours. Adding specific hours will increase automated booking conversions.",
    priority: "medium",
    actionLabel: "Update KB",
  },
  {
    id: "rec_3",
    title: "Upcoming slot under-booked: Wed 2-5 PM",
    description: "Mid-week clinical training slots are empty. Trigger automated promo message to 14 warm leads who inquired about rehab.",
    priority: "low",
    actionLabel: "Send Campaign",
  },
]

export const systemStatus: SystemStatus = {
  whatsappConnected: true,
  ragIndexSynced: true,
  apiLatencyMs: 142,
  whatsappLatencyMs: 280,
}

export const evaluationMetrics: EvaluationMetric = {
  latencySec: 1.45,
  confidenceScore: 0.942,
  groundedRate: 0.985,
  hallucinationRate: 0.0,
}

export const initialKnowledgeDocuments: KnowledgeDocument[] = [
  {
    id: "kd_1",
    title: "Premium Gym Memberships",
    type: "PRICING",
    content: `Veda Wellness offers premium gym memberships:
- Monthly: ₹2,500
- Quarterly: ₹6,500
- Semi-Annual: ₹12,000
- Annual Performance Package: ₹18,000

All packages include access to the medical gym, lockers, and 2 general physical fitness assessments.`,
    uploadedAt: "2026-07-01",
  },
  {
    id: "kd_2",
    title: "Physiotherapy & Rehab Packages",
    type: "SERVICE",
    content: `Sports Physiotherapy and Rehab Services:
- Single Assessment Session: ₹1,800
- Elite Rehab Package (10 sessions): ₹15,000
- Specialist Orthopedic Consultation: ₹2,500

We focus on lower body rehab, knee/shoulder recovery, and posture correction.`,
    uploadedAt: "2026-07-02",
  },
  {
    id: "kd_3",
    title: "Nutrition & Metabolic Consults",
    type: "SERVICE",
    content: `Nutrition Packages:
- Metabolic Assessment & Scan: ₹3,500
- Custom Diet Chart Plan: ₹5,000
- Monthly Diet Follow-ups: ₹2,500

Our senior clinical nutritionist is available on Saturdays from 9 AM to 2 PM. Booking in advance is required.`,
    uploadedAt: "2026-07-03",
  },
  {
    id: "kd_4",
    title: "Parking & Valet Policy",
    type: "POLICY",
    content: `Parking is available at all our Indiranagar branches. 
The Indiranagar branch has dedicated basement parking for Veda Wellness members, free of charge. Security guards will assist with valet parking.`,
    uploadedAt: "2026-07-04",
  },
  {
    id: "kd_5",
    title: "Indiranagar Center Hours",
    type: "FAQ",
    content: `Veda Wellness Indiranagar Operating Hours:
- Monday to Friday: 5:30 AM to 10:00 PM
- Saturday: 6:00 AM to 8:00 PM
- Sunday: Closed for deep sanitization.
Physiotherapists are available from 7:00 AM to 8:00 PM on weekdays.`,
    uploadedAt: "2026-07-05",
  },
  {
    id: "kd_6",
    title: "What to wear to first Physiotherapy slot?",
    type: "FAQ",
    content: `For orthopedic or sports assessment sessions, please wear loose athletic attire (t-shirts, track pants, shorts) that allows easy access to joints. Bring any past MRI/X-Ray medical scan reports and doctor prescriptions.`,
    uploadedAt: "2026-07-06",
  },
  {
    id: "kd_7",
    title: "Monsoon Rehab Launch Offer",
    type: "OFFER",
    content: `Veda Monsoon Kickstart Offer:
Sign up for a 10-session Elite Rehab Program in July and receive 15% off (discounted value: ₹12,750 instead of ₹15,000). Offer ends July 31. Promo Code: MONSOON15.`,
    uploadedAt: "2026-07-07",
  },
  {
    id: "kd_8",
    title: "Appointment Cancellation Policy",
    type: "POLICY",
    content: `Veda Wellness Cancellation Policy:
Please notify us at least 4 hours in advance to reschedule or cancel a session. Same-day cancellations within 4 hours of the slot incur a 50% session deduction fee. No-shows will be charged at 100% value.`,
    uploadedAt: "2026-07-08",
  },
  {
    id: "kd_9",
    title: "Elite Athlete Cardiorespiratory Assessment",
    type: "SERVICE",
    content: `VO2 Max & Lactate Threshold Testing:
- Single Assessment: ₹6,500.
Includes complete metabolic profile, treadmill gas-exchange analysis, and lactate profiling with senior cardiac fitness specialists. Required booking 48h in advance.`,
    uploadedAt: "2026-07-09",
  },
  {
    id: "kd_10",
    title: "Corporate Member Discount Plans",
    type: "OFFER",
    content: `Corporate Wellness Discounts:
Employees of tied-up firms (Infosys, Wipro, TCS, Goldman Sachs) receive 10% flat off on monthly gym memberships and clinical wellness plans. Valid corporate ID badge required during registration.`,
    uploadedAt: "2026-07-10",
  },
]

export const initialLeads: LeadItem[] = [
  {
    id: "l_1",
    name: "Rohan Sharma",
    phoneNumber: "+91 98450 12345",
    status: "Engaged",
    leadScore: 92,
    bookingProbability: 85,
    intent: "high-intent",
    urgency: "Immediate",
    sentiment: "Positive",
    reasoning: "Inquired about lower body rehab coaching slot. Responded instantly to slot options, checked packages pricing twice.",
    lastContact: "3h ago",
  },
  {
    id: "l_2",
    name: "Dr. Ananya Iyer",
    phoneNumber: "+91 99160 88776",
    status: "New",
    leadScore: 88,
    bookingProbability: 70,
    intent: "high-intent",
    urgency: "Within 48h",
    sentiment: "Inquisitive",
    reasoning: "Inquired about clinical nutritionist availability for Saturday session to share blood reports. High-intent medical context.",
    lastContact: "12m ago",
  },
  {
    id: "l_3",
    name: "Priya Nair",
    phoneNumber: "+91 97312 99881",
    status: "Engaged",
    leadScore: 84,
    bookingProbability: 65,
    intent: "high-intent",
    urgency: "Within 48h",
    sentiment: "Neutral",
    reasoning: "Inquired about membership fees for annual wellness package. Checked wellness plan details, waiting on pricing decisions.",
    lastContact: "3h ago",
  },
  {
    id: "l_4",
    name: "Amit Patel",
    phoneNumber: "+91 98801 44332",
    status: "Qualified",
    leadScore: 78,
    bookingProbability: 58,
    intent: "follow-up",
    urgency: "Medium",
    sentiment: "Positive",
    reasoning: "Completed metabolic scan, requested custom diet proposal. Sent nudged reminders, hasn't scheduled slot yet.",
    lastContact: "4h ago",
  },
  {
    id: "l_5",
    name: "Vikram Malhotra",
    phoneNumber: "+91 96112 55443",
    status: "Booked",
    leadScore: 95,
    bookingProbability: 95,
    intent: "follow-up",
    urgency: "Immediate",
    sentiment: "Positive",
    reasoning: "Confirmed Elite Rehab slot at 04:30 PM today. Downloaded diet PDF successfully, active conversion track.",
    lastContact: "1d ago",
  },
  {
    id: "l_6",
    name: "Arjun Mehta",
    phoneNumber: "+91 95350 77665",
    status: "Converted",
    leadScore: 100,
    bookingProbability: 100,
    intent: "support",
    urgency: "Low",
    sentiment: "Positive",
    reasoning: "Upgraded to Annual Performance Program (₹45,000 package value). Requested session rescheduling from today to Thursday.",
    lastContact: "5h ago",
  },
  {
    id: "l_7",
    name: "Kavita Reddy",
    phoneNumber: "+91 94480 33221",
    status: "Churned",
    leadScore: 35,
    bookingProbability: 10,
    intent: "cold",
    urgency: "Low",
    sentiment: "Neutral",
    reasoning: "Only asked about parking availability at Indiranagar branch. No follow up inquiries about coaching slots or prices.",
    lastContact: "1d ago",
  },
  {
    id: "l_8",
    name: "Devendra Singh",
    phoneNumber: "+91 98765 43210",
    status: "Engaged",
    leadScore: 65,
    bookingProbability: 40,
    intent: "follow-up",
    urgency: "Medium",
    sentiment: "Inquisitive",
    reasoning: "Requested list of active corporate wellness tie-ups. Interested in group rehabilitation discounts for employees.",
    lastContact: "2h ago",
  },
  {
    id: "l_9",
    name: "Meera Nair",
    phoneNumber: "+91 97654 32109",
    status: "New",
    leadScore: 40,
    bookingProbability: 15,
    intent: "cold",
    urgency: "Low",
    sentiment: "Neutral",
    reasoning: "Asked for geographical directions to the Whitefield center. No queries about assessments, trials, or coaches.",
    lastContact: "6h ago",
  },
  {
    id: "l_10",
    name: "Sanjay Singhal",
    phoneNumber: "+91 96543 21098",
    status: "Qualified",
    leadScore: 90,
    bookingProbability: 80,
    intent: "high-intent",
    urgency: "Immediate",
    sentiment: "Positive",
    reasoning: "Requested trainer bio details for ACL recovery. Checked package costs and verified clinical references.",
    lastContact: "30m ago",
  },
  {
    id: "l_11",
    name: "Pooja Hegde",
    phoneNumber: "+91 95432 10987",
    status: "Engaged",
    leadScore: 72,
    bookingProbability: 50,
    intent: "follow-up",
    urgency: "Medium",
    sentiment: "Inquisitive",
    reasoning: "Inquired about Saturday morning clinical yoga schedules. Checked class sizes but hasn't committed to a trial slot.",
    lastContact: "4h ago",
  },
  {
    id: "l_12",
    name: "Rajesh Khanna",
    phoneNumber: "+91 94321 09876",
    status: "Churned",
    leadScore: 25,
    bookingProbability: 5,
    intent: "cold",
    urgency: "Low",
    sentiment: "Frustrated",
    reasoning: "Lodged a complaint about locker room air conditioning at Indiranagar branch. Inactive lead with no conversion interest.",
    lastContact: "2d ago",
  },
  {
    id: "l_13",
    name: "Neha Deshmukh",
    phoneNumber: "+91 93210 98765",
    status: "Booked",
    leadScore: 86,
    bookingProbability: 90,
    intent: "high-intent",
    urgency: "Immediate",
    sentiment: "Positive",
    reasoning: "Booked Diagnostic Assessment for tomorrow. Transacted booking payment online, highly likely to buy membership package.",
    lastContact: "1h ago",
  },
  {
    id: "l_14",
    name: "Abhishek Bachchan",
    phoneNumber: "+91 92109 87654",
    status: "New",
    leadScore: 60,
    bookingProbability: 30,
    intent: "support",
    urgency: "Low",
    sentiment: "Neutral",
    reasoning: "Inquired about shower amenities, towel services, and lockers availability. Generic facility check, warm interest.",
    lastContact: "7h ago",
  },
  {
    id: "l_15",
    name: "Karan Johar",
    phoneNumber: "+91 91098 76543",
    status: "Engaged",
    leadScore: 30,
    bookingProbability: 8,
    intent: "cold",
    urgency: "Low",
    sentiment: "Neutral",
    reasoning: "Sent generic forwarded WhatsApp greetings. AI filter categorized as low value lead, general chat.",
    lastContact: "10h ago",
  },
  {
    id: "l_16",
    name: "Shreya Ghoshal",
    phoneNumber: "+91 90987 65432",
    status: "Converted",
    leadScore: 100,
    bookingProbability: 100,
    intent: "high-intent",
    urgency: "Low",
    sentiment: "Positive",
    reasoning: "Completed metabolic assessments, purchased 3-month medical gym membership (₹6,500 package). Active onboarding tracker.",
    lastContact: "1d ago",
  },
  {
    id: "l_17",
    name: "Sunita Williams",
    phoneNumber: "+91 89876 54321",
    status: "Qualified",
    leadScore: 70,
    bookingProbability: 55,
    intent: "follow-up",
    urgency: "Medium",
    sentiment: "Inquisitive",
    reasoning: "Inquired about cardiovascular rehab programs for senior citizens. Shared clinical reports, requested slot pricing options.",
    lastContact: "5h ago",
  },
  {
    id: "l_18",
    name: "Vijay Mallya",
    phoneNumber: "+91 88765 43210",
    status: "Churned",
    leadScore: 15,
    bookingProbability: 2,
    intent: "cold",
    urgency: "Low",
    sentiment: "Neutral",
    reasoning: "Asked if annual performance plans support credit card EMI. Disappeared when card processing rules were explained.",
    lastContact: "3d ago",
  },
]
